apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-configuration
spec:
  rules:
  - host: {{.Values.appURL}}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{.Values.mysvcname}}
          servicePort: {{.Values.mysvcport}}
